# SQL Selection II

**Dr. Pengfei Zhao**

Finance Mathematics Program, 

BNU-HKBU United International College

In [ ]:
%load_ext sql
import pymysql
pymysql.install_as_MySQLdb()

%sql mysql://few:123456@localhost/HelloDB?charset=utf8

In [2]:
%sql SHOW TABLES;

4 rows affected.

[('company_info',),
 ('hundred_stocks_twoyears_daily_bar',),
 ('sh50',),
 ('sh50_oneyear_dailybar',)]

In [ ]:
%sql ALTER TABLE company_info MODIFY code bigint(20);

In [5]:
import pandas as pd
from sqlalchemy import create_engine
conn = create_engine("mysql+pymysql://{user}:{pw}@localhost/{db}?charset=utf8" \
                            .format(user="few", pw="123456", db="HelloDB"))

df_sh50 = pd.read_sql('select * from sh50', con=conn)
df_company = pd.read_sql('select * from company_info', con=conn)
df_sh50_1year = pd.read_sql('select * from sh50_oneyear_dailybar', con=conn)

## 12. `AS`

* SQL aliases are used to give a table, or a column in a table, a temporary name.

* Aliases are often used to make column names more readable.

* An alias only exists for the duration of the query.

**Syntax**

>```SQL
SELECT column_name AS alias_name FROM table_name;
```
>```SQL
SELECT column_name(s) FROM table_name AS alias_name;
```

## 13. `Joins`

* A `JOIN` clause is used to combine rows from **two or more** tables, based on a related column between them.

* There are the different types of the JOINs in SQL:

    * (INNER) JOIN: Returns records that have matching values in both tables
    * LEFT (OUTER) JOIN: Return all records from the left table, and the matched records from the right table
    * RIGHT (OUTER) JOIN: Return all records from the right table, and the matched records from the left table
    * FULL (OUTER) JOIN: Return all records when there is a match in either left or right table

 <img src="../Figures/DB/join.png" width = "480" height = "350" alt="图片名称" align=center />

In [6]:
df_sh50.head()

     code  name  weight
0  603993  洛阳钼业    0.40
1  601989  中国重工    1.08
2  601988  中国银行    1.79
3  601985  中国核电    0.64
4  601881  中国银河    0.14

In [7]:
df_sh50.shape

(50, 3)

In [8]:
df_company.head()

,index,code,name,industry,area,pe,outstanding,totals,totalAssets,liquidAssets,...,bvps,pb,timeToMarket,undp,perundp,rev,profit,gpr,npr,holders
0,0,300722,N新余,专用机械,江西,28.10,0.20,0.80,43229.96,20194.17,...,3.69,3.51,20171110,6789.25,0.85,0.0,0.0,47.23,19.67,40001.0
1,1,603916,N苏博特,化工原料,江苏,25.74,0.76,3.04,249746.05,140487.80,...,5.41,2.40,20171110,48729.50,1.60,0.0,0.0,39.04,9.76,68785.0
2,2,300725,N药石,化工原料,江苏,17.03,0.18,0.73,36124.62,22444.40,...,5.42,3.01,20171110,6652.74,0.91,0.0,0.0,64.88,26.89,36669.0
3,3,603083,N剑桥,通信设备,上海,28.87,0.24,0.98,184472.72,123587.26,...,9.91,2.19,20171110,34414.28,3.52,0.0,0.0,15.45,2.98,27584.0
4,4,600903,贵州燃气,供气供热,贵州,25.26,1.22,8.13,751383.75,143656.61,...,3.30,1.28,20171107,18899.70,0.23,0.0,0.0,21.46,5.34,106254.0

In [9]:
df_company.shape

(3445, 24)

### 13.1 (INNER) JOIN

* Returns records that have matching values in both tables.

**Syntax**

>```SQL
SELECT column_name(s) FROM table1 INNER JOIN table2 ON table1.column_name = table2.column_name;
```

**Example**

In [10]:
%sql SELECT COUNT(*) FROM company_info;

1 rows affected.

[(3445,)]

In [11]:
%sql SELECT COUNT(*) FROM sh50;

1 rows affected.

[(50,)]

In [13]:
%sql SELECT count(*) FROM company_info JOIN sh50 ON company_info.code = sh50.code;

1 rows affected.

[(50,)]

In [14]:
%sql SELECT * FROM company_info JOIN sh50 ON company_info.code = sh50.code LIMIT 10;

10 rows affected.

[('601336', '新华保险', '保险', '北京', 31.25, 3.3, 71477104.0, 601336, '新华保险', 0.93),
 ('601318', '中国平安', '保险', '深圳', 14.45, 2.85, 616851584.0, 601318, '中国平安', 15.48),
 ('601601', '中国太保', '保险', '上海', 27.63, 2.96, 116817904.0, 601601, '中国太保', 2.34),
 ('600519', '贵州茅台', '白酒', '贵州', 31.96, 10.1, 12778004.0, 600519, '贵州茅台', 7.06),
 ('601628', '中国人寿', '保险', '北京', 26.89, 3.05, 286852512.0, 601628, '中国人寿', 0.94),
 ('600887', '伊利股份', '乳制品', '内蒙', 28.49, 7.75, 4713239.5, 600887, '伊利股份', 3.91),
 ('600104', '上汽集团', '汽车整车', '上海', 11.54, 1.76, 65232296.0, 600104, '上汽集团', 2.16),
 ('600029', '南方航空', '空运', '广东', 9.8, 1.82, 21133400.0, 600029, '南方航空', 0.67),
 ('601878', '浙商证券', '证券', '浙江', 56.6, 4.66, 5144893.0, 601878, '浙商证券', 0.12),
 ('600050', '中国联通', '电信运营', '上海', 142.59, 2.22, 59056808.0, 600050, '中国联通', 1.15)]

In [60]:
import pandas as pd
df = pd.merge(df_company, df_sh50, on='code', how='inner')

In [61]:
df.shape

(50, 9)

In [62]:
df.head()

     code name_x industry area     pe     pb  totalAssets name_y  weight
0  601336   新华保险       保险   北京  31.25   3.30   71477104.0   新华保险    0.93
1  601318   中国平安       保险   深圳  14.45   2.85  616851584.0   中国平安   15.48
2  601601   中国太保       保险   上海  27.63   2.96  116817904.0   中国太保    2.34
3  600519   贵州茅台       白酒   贵州  31.96  10.10   12778004.0   贵州茅台    7.06
4  601628   中国人寿       保险   北京  26.89   3.05  286852512.0   中国人寿    0.94

### 13.2 LEFT (OUTER) JOIN

* The `LEFT JOIN` keyword returns **all** records from the left table (table1), and the matched records from the right table (table2). The result is **NULL** from the right side, if there is no match.

**Syntax**

>```SQL
SELECT column_name(s) FROM table1 LEFT JOIN table2 ON table1.column_name = table2.column_name;
```

**Example**

* Following previous example in 12.1:

In [15]:
%sql SELECT count(*) FROM company_info LEFT JOIN sh50 ON company_info.code = sh50.code;

1 rows affected.

[(3445,)]

In [18]:
%sql SELECT * FROM company_info LEFT JOIN sh50 ON company_info.code = sh50.code LIMIT 100;

100 rows affected.

[('603993', '洛阳钼业', '小金属', '河南', 68.25, 3.92, 10020716.0, 603993, '洛阳钼业', 0.4),
 ('601989', '中国重工', '船舶', '北京', 84.29, 1.95, 20866086.0, 601989, '中国重工', 1.08),
 ('601988', '中国银行', '银行', '北京', 5.87, 0.83, 1942243712.0, 601988, '中国银行', 1.79),
 ('601985', '中国核电', '新型电力', '北京', 21.96, 2.79, 30007324.0, 601985, '中国核电', 0.64),
 ('601881', '中国银河', '证券', '北京', 30.29, 2.13, 24398524.0, 601881, '中国银河', 0.14),
 ('601878', '浙商证券', '证券', '浙江', 56.6, 4.66, 5144893.0, 601878, '浙商证券', 0.12),
 ('601857', '中国石油', '石油开采', '北京', 66.33, 1.29, 244611104.0, 601857, '中国石油', 1.08),
 ('601818', '光大银行', '银行', '北京', 5.51, 0.77, 403041408.0, 601818, '光大银行', 1.39),
 ('601800', '中国交建', '建筑施工', '北京', 15.3, 1.38, 88370472.0, 601800, '中国交建', 0.4),
 ('601766', '中国中车', '运输设备', '北京', 34.49, 2.66, 37577796.0, 601766, '中国中车', 1.66),
 ('601688', '华泰证券', '证券', '江苏', 23.13, 1.69, 37462496.0, 601688, '华泰证券', 1.22),
 ('601669', '中国电建', '建筑施工', '北京', 15.07, 1.48, 58281880.0, 601669, '中国电建', 0.64),
 ('601668', '中国建筑', '建筑施工', '北京', 8.25, 1.37, 152710720.0, 601668, '中国建筑', 2.87),
 ('601628', '中国人寿', '保险', '北京', 26.89, 3.05, 286852512.0, 601628, '中国人寿', 0.94),
 ('601601', '中国太保', '保险', '上海', 27.63, 2.96, 116817904.0, 601601, '中国太保', 2.34),
 ('601398', '工商银行', '银行', '北京', 6.82, 1.04, 2576479744.0, 601398, '工商银行', 2.93),
 ('601390', '中国中铁', '建筑施工', '北京', 13.66, 1.34, 78568864.0, 601390, '中国中铁', 0.88),
 ('601336', '新华保险', '保险', '北京', 31.25, 3.3, 71477104.0, 601336, '新华保险', 0.93),
 ('601328', '交通银行', '银行', '上海', 6.25, 0.76, 893579072.0, 601328, '交通银行', 3.48),
 ('601318', '中国平安', '保险', '深圳', 14.45, 2.85, 616851584.0, 601318, '中国平安', 15.48),
 ('601288', '农业银行', '银行', '北京', 5.53, 0.89, 2092311808.0, 601288, '农业银行', 3.11),
 ('601229', '上海银行', '银行', '上海', 8.63, 1.08, 175999888.0, 601229, '上海银行', 0.25),
 ('601211', '国泰君安', '证券', '上海', 18.84, 1.46, 41555676.0, 601211, '国泰君安', 1.41),
 ('601186', '中国铁建', '建筑施工', '北京', 11.47, 1.15, 82964336.0, 601186, '中国铁建', 1.0),
 ('601169', '北京银行', '银行', '北京', 6.42, 0.87, 227522592.0, 601169, '北京银行', 2.05),
 ('601166', '兴业银行', '银行', '福建', 5.6, 0.92, 640699328.0, 601166, '兴业银行', 4.14),
 ('601088', '中国神华', '煤炭开采', '北京', 9.04, 1.47, 56003400.0, 601088, '中国神华', 0.9),
 ('601006', '大秦铁路', '铁路', '山西', 8.77, 1.35, 12906953.0, 601006, '大秦铁路', 1.09),
 ('600999', '招商证券', '证券', '深圳', 23.44, 1.66, 25777122.0, 600999, '招商证券', 0.81),
 ('600958', '东方证券', '证券', '上海', 28.55, 2.4, 22343832.0, 600958, '东方证券', 0.81),
 ('600919', '江苏银行', '银行', '江苏', 7.49, 1.03, 173756544.0, 600919, '江苏银行', 1.03),
 ('600887', '伊利股份', '乳制品', '内蒙', 28.49, 7.75, 4713239.5, 600887, '伊利股份', 3.91),
 ('600837', '海通证券', '证券', '上海', 20.41, 1.44, 52946080.0, 600837, '海通证券', 2.07),
 ('600606', '绿地控股', '全国地产', '上海', 10.43, 1.52, 77101312.0, 600606, '绿地控股', 0.65),
 ('600547', '山东黄金', '黄金', '山东', 46.69, 3.43, 4219631.5, 600547, '山东黄金', 0.44),
 ('600519', '贵州茅台', '白酒', '贵州', 31.96, 10.1, 12778004.0, 600519, '贵州茅台', 7.06),
 ('600518', '康美药业', '中成药', '广东', 26.56, 3.59, 6533670.5, 600518, '康美药业', 1.16),
 ('600340', '华夏幸福', '区域地产', '河北', 10.83, 3.34, 33648380.0, 600340, '华夏幸福', 0.94),
 ('600309', '万华化学', '化工原料', '山东', 9.64, 4.19, 6275300.0, 600309, '万华化学', 0.94),
 ('600111', '北方稀土', '小金属', '内蒙', 111.69, 5.9, 2202781.75, 600111, '北方稀土', 0.58),
 ('600104', '上汽集团', '汽车整车', '上海', 11.54, 1.76, 65232296.0, 600104, '上汽集团', 2.16),
 ('600050', '中国联通', '电信运营', '上海', 142.59, 2.22, 59056808.0, 600050, '中国联通', 1.15),
 ('600048', '保利地产', '全国地产', '广东', 11.23, 1.31, 63262392.0, 600048, '保利地产', 2.29),
 ('600036', '招商银行', '银行', '深圳', 8.71, 1.56, 616923904.0, 600036, '招商银行', 6.37),
 ('600030', '中信证券', '证券', '深圳', 21.08, 1.52, 63177336.0, 600030, '中信证券', 3.03),
 ('600029', '南方航空', '空运', '广东', 9.8, 1.82, 21133400.0, 600029, '南方航空', 0.67),
 ('600028', '中国石化', '石油加工', '北京', 14.41, 1.03, 147665504.0, 600028, '中国石化', 1.34),
 ('600019', '宝钢股份', '普钢', '上海', 11.85, 1.17, 34661280.0, 600019, '宝钢股份', 1.48),
 ('600016', '民生银行', '银行', '北京', 5.72, 0.85, 571252480.0, 600016, '民生银行', 3.96),
 ('600000', '浦发银行', '银行', '上海', 6.64, 0.96, 606383680.0, 600000, '浦发银行', 2.75),
 ('300722', 'N新余', '专用机械', '江西', 28.1, 3.51, 43229.96, None, None, None),
 ('603916', 'N苏博特', '化工原料', '江苏', 25.74, 2.4, 249746.05, None, None, None),
 ('300725', 'N药石', '化工原料', '江苏', 17.03, 3.01, 36124.62, None, None, None),
 ('603083', 'N剑桥', '通信设备', '上海', 28.87, 2.19, 184472.72, None, None, None),
 ('600903', '贵州燃气', '供气供热', '贵州', 25.26, 1.28, 751383.75, None, None, None),
 ('600460', '士兰微', '半导体', '浙江', 76.67, 5.33, 594216.69, None, None, None),
 ('600621', '华鑫股份', '证券', '上海', 89.22, 2.29, 1624948.5, None, None, None),
 ('300719', '安达维尔', '航空', '北京', 317.04, 5.98, 58974.3, None, None, None),
 ('603920', '世运电路', '元器件', '广东', 43.0, 3.91, 294390.53, None, None, None),
 ('002908', '德生科技', '元器件', '广东', 99.4, 9.66, 52750.28, None, None, None),
 ('603659', '璞泰来', '化工原料', '上海', 38.41, 10.71, 289609.25, None, None, None),
 ('002909', '集泰股份', '化工原料', '广东', 61.69, 7.98, 62304.0, None, None, None),
 ('000004', '国农科技', '生物制药', '深圳', 0.0, 18.87, 24121.07, None, None, None),
 ('600167', '联美控股', '供气供热', '辽宁', 37.71, 3.46, 997789.81, None, None, None),
 ('300716', '国立科技', '塑料', '广东', 40.32, 3.16, 72146.3, None, None, None),
 ('600559', '老白干酒', '白酒', '河北', 84.48, 7.9, 289922.47, None, None, None),
 ('002907', '华森制药', '化学制药', '重庆', 72.88, 14.63, 70735.78, None, None, None),
 ('603856', '东宏股份', '塑料', '山东', 33.22, 3.68, 137082.3, None, None, None),
 ('300712', '永福股份', '建筑施工', '福建', 66.79, 8.04, 79420.17, None, None, None),
 ('600438', '通威股份', '饲料', '四川', 23.66, 3.74, 2513550.0, None, None, None),
 ('300718', '长盛轴承', '机械基件', '浙江', 31.54, 5.18, 65926.93, None, None, None),
 ('300414', '中光防雷', '元器件', '四川', 113.36, 5.84, 92818.34, None, None, None),
 ('603501', '韦尔股份', '半导体', '上海', 134.99, 15.89, 204200.45, None, None, None),
 ('600345', '长江通信', '通信设备', '湖北', 21.86, 3.9, 169018.81, None, None, None),
 ('603260', '合盛硅业', '化工原料', '浙江', 34.47, 11.01, 1137959.63, None, None, None),
 ('300711', '广哈通信', '通信设备', '广东', 71.66, 9.44, 34718.62, None, None, None),
 ('603289', '泰瑞机器', '专用机械', '浙江', 58.58, 7.22, 88554.82, None, None, None),
 ('300620', '光库科技', '元器件', '广东', 75.0, 9.16, 52511.7, None, None, None),
 ('300713', '英可瑞', '电气设备', '深圳', 69.86, 15.69, 48435.67, None, None, None),
 ('603396', '金辰股份', '专用机械', '辽宁', 61.12, 7.01, 95960.03, None, None, None),
 ('601313', '江南嘉捷', '运输设备', '江苏', 85.52, 3.06, 263963.25, None, None, None),
 ('300717', '华信新材', '塑料', '江苏', 43.84, 4.88, 37774.01, None, None, None),
 ('300619', '金银河', '专用机械', '广东', 93.34, 12.08, 80837.45, None, None, None),
 ('300322', '硕贝德', '通信设备', '广东', 133.84, 8.43, 284782.22, None, None, None),
 ('002618', '丹邦科技', '元器件', '深圳', 336.83, 4.47, 249018.52, None, None, None),
 ('603507', '振江股份', '钢加工', '江苏', 49.48, 8.29, 119813.13, None, None, None),
 ('603722', '阿科力', '化工原料', '江苏', 81.36, 11.12, 46842.09, None, None, None),
 ('300715', '凯伦股份', '其他建材', '江苏', 97.36, 16.01, 40622.2, None, None, None),
 ('603729', '龙韵股份', '广告包装', '上海', 288.82, 6.87, 97434.93, None, None, None),
 ('300720', '海川智能', '电器仪表', '广东', 56.71, 5.61, 29150.1, None, None, None),
 ('002409', '雅克科技', '化工原料', '江苏', 211.42, 9.02, 179658.88, None, None, None),
 ('300655', '晶瑞股份', '化工原料', '江苏', 113.73, 8.41, 71158.15, None, None, None),
 ('300502', '新易盛', '通信设备', '四川', 66.42, 7.87, 135900.52, None, None, None),
 ('603559', '中通国脉', '通信设备', '吉林', 326.32, 12.42, 78824.17, None, None, None),
 ('300462', '华铭智能', '专用机械', '上海', 160.35, 9.81, 81888.28, None, None, None),
 ('300054', '鼎龙股份', '化工原料', '湖北', 36.67, 3.21, 397465.5, None, None, None),
 ('002910', '庄园牧场', '乳制品', '甘肃', 59.59, 4.04, 145640.73, None, None, None),
 ('601012', '隆基股份', '半导体', '陕西', 26.18, 6.43, 2948550.25, None, None, None),
 ('603690', '至纯科技', '专用机械', '上海', 116.82, 14.12, 95762.72, None, None, None),
 ('300708', '聚灿光电', '半导体', '江苏', 51.78, 8.74, 113054.97, None, None, None)]

* You can see many **none** in the table, which is because their exists companies only in `company_info` table, rather than `sh50` table.

In [63]:
df_left = pd.merge(df_company, df_sh50, on='code', how='left')

In [64]:
df_left.shape

(3445, 9)

In [65]:
df_left.tail()

        code name_x industry area   pe   pb  totalAssets name_y  weight
3440  300727   润禾材料     化工原料   浙江  0.0  0.0     43196.92    NaN     NaN
3441  300723    一品红     化学制药   广东  0.0  0.0     76309.68    NaN     NaN
3442  300721   怡达股份     化工原料   江苏  0.0  0.0     88405.46    NaN     NaN
3443    2912   中新赛克     软件服务   深圳  0.0  0.0     95634.96    NaN     NaN
3444    2911   佛燃股份     供气供热   广东  0.0  0.0    441762.84    NaN     NaN

### 13.3 RIGHT JOIN Keyword

* The RIGHT JOIN keyword returns all records from the right table (table2), and the matched records from the left table (table1). The result is NULL from the left side, when there is no match.

**Syntax**

>```SQL
SELECT column_name(s) FROM table1 RIGHT JOIN table2 ON table1.column_name = table2.column_name;
```

**Example**

In [66]:
%sql SELECT COUNT(*) FROM company_info RIGHT JOIN sh50 ON company_info.code=sh50.code

1 rows affected.

[(50,)]

In [67]:
%sql SELECT * FROM company_info RIGHT JOIN sh50 ON company_info.code=sh50.code LIMIT 10

10 rows affected.

[(601336, '新华保险', '保险', '北京', 31.25, 3.3, 71477104.0, 601336, '新华保险', 0.93),
 (601318, '中国平安', '保险', '深圳', 14.45, 2.85, 616851584.0, 601318, '中国平安', 15.48),
 (601601, '中国太保', '保险', '上海', 27.63, 2.96, 116817904.0, 601601, '中国太保', 2.34),
 (600519, '贵州茅台', '白酒', '贵州', 31.96, 10.1, 12778004.0, 600519, '贵州茅台', 7.06),
 (601628, '中国人寿', '保险', '北京', 26.89, 3.05, 286852512.0, 601628, '中国人寿', 0.94),
 (600887, '伊利股份', '乳制品', '内蒙', 28.49, 7.75, 4713239.5, 600887, '伊利股份', 3.91),
 (600104, '上汽集团', '汽车整车', '上海', 11.54, 1.76, 65232296.0, 600104, '上汽集团', 2.16),
 (600029, '南方航空', '空运', '广东', 9.8, 1.82, 21133400.0, 600029, '南方航空', 0.67),
 (601878, '浙商证券', '证券', '浙江', 56.6, 4.66, 5144893.0, 601878, '浙商证券', 0.12),
 (600050, '中国联通', '电信运营', '上海', 142.59, 2.22, 59056808.0, 600050, '中国联通', 1.15)]

### 13.4 SELF JOIN Keyword

* A self JOIN is a regular join, but the table is joined with itself.

**Syntax**

>```SQL
SELECT column_name(s) FROM table1 T1, table1 T2 WHERE condition;
```

**Example**

* select all SSH50 index stocks which are in the same industry

In [74]:
%sql SELECT A.name AS name1, B.name AS name2, A.industry FROM company_info A, \
        company_info B where A.name <>B.name and A.industry=B.industry LIMIT 20;

20 rows affected.

[('泰瑞机器', 'N新余', '专用机械'),
 ('金辰股份', 'N新余', '专用机械'),
 ('金银河', 'N新余', '专用机械'),
 ('华铭智能', 'N新余', '专用机械'),
 ('至纯科技', 'N新余', '专用机械'),
 ('佳力图', 'N新余', '专用机械'),
 ('台海核电', 'N新余', '专用机械'),
 ('新元科技', 'N新余', '专用机械'),
 ('弘宇股份', 'N新余', '专用机械'),
 ('金盾股份', 'N新余', '专用机械'),
 ('金雷风电', 'N新余', '专用机械'),
 ('长川科技', 'N新余', '专用机械'),
 ('科森科技', 'N新余', '专用机械'),
 ('华舟应急', 'N新余', '专用机械'),
 ('银都股份', 'N新余', '专用机械'),
 ('宏盛股份', 'N新余', '专用机械'),
 ('豪迈科技', 'N新余', '专用机械'),
 ('美亚光电', 'N新余', '专用机械'),
 ('中金环境', 'N新余', '专用机械'),
 ('海陆重工', 'N新余', '专用机械')]

## 14. `groupby`

### 14.1 Basic `Group By`

* With what you learned in Pandas DataFrame `groupby`, you should be familiar with the concept here.
* The `GROUP BY` statement is often used with aggregate functions (COUNT, MAX, MIN, SUM, AVG) to group the result-set by one or more columns.
* The aggregate function works on each group **separately**.
* Every column not in the `GROUP BY` clause must have a function applied to reduce all records for the matching "group" to a single record (sum, max, min, etc).

**Syntax**

>```SQL
SELECT Agg(), column_name(s) FROM table_name WHERE condition GROUP BY column_name(s)
```

**Example**

In [79]:
%sql describe company_info

7 rows affected.

[('code', 'bigint(20)', 'YES', '', None, ''),
 ('name', 'text', 'YES', '', None, ''),
 ('industry', 'text', 'YES', '', None, ''),
 ('area', 'text', 'YES', '', None, ''),
 ('pe', 'double', 'YES', '', None, ''),
 ('pb', 'double', 'YES', '', None, ''),
 ('totalAssets', 'double', 'YES', '', None, '')]

In [82]:
%sql SELECT COUNT(*) AS number, area FROM company_info GROUP BY area ORDER BY number DESC;

32 rows affected.

[(411, '浙江'),
 (379, '江苏'),
 (304, '北京'),
 (293, '广东'),
 (274, '上海'),
 (266, '深圳'),
 (194, '山东'),
 (131, '福建'),
 (114, '四川'),
 (102, '安徽'),
 (100, '湖南'),
 (96, '湖北'),
 (77, '河南'),
 (74, '辽宁'),
 (55, '河北'),
 (51, '新疆'),
 (49, '天津'),
 (49, '重庆'),
 (47, '陕西'),
 (42, '吉林'),
 (38, '江西'),
 (38, '山西'),
 (36, '广西'),
 (36, '黑龙江'),
 (34, '云南'),
 (33, '甘肃'),
 (30, '海南'),
 (27, '贵州'),
 (25, '内蒙'),
 (15, '西藏'),
 (13, '宁夏'),
 (12, '青海')]

In [84]:
%sql SELECT COUNT(*) AS number, industry FROM company_info GROUP BY industry ORDER BY number DESC;

110 rows affected.

[(160, '软件服务'),
 (159, '电气设备'),
 (154, '元器件'),
 (152, '化工原料'),
 (128, '专用机械'),
 (117, '汽车配件'),
 (108, '通信设备'),
 (86, '建筑施工'),
 (83, '化学制药'),
 (75, '中成药'),
 (71, '区域地产'),
 (70, '机械基件'),
 (63, '医疗保健'),
 (60, '电器仪表'),
 (59, '环境保护'),
 (57, '半导体'),
 (55, '服饰'),
 (54, '食品'),
 (50, '互联网'),
 (48, '百货'),
 (48, '纺织'),
 (47, '农药化肥'),
 (44, '塑料'),
 (42, '家用电器'),
 (42, '影视音像'),
 (41, '生物制药'),
 (38, '全国地产'),
 (36, '广告包装'),
 (34, '证券'),
 (34, '火力发电'),
 (33, '电脑设备'),
 (33, '家居用品'),
 (33, '小金属'),
 (31, '工程机械'),
 (30, '综合类'),
 (30, '煤炭开采'),
 (29, '仓储物流'),
 (28, '文教休闲'),
 (27, '装修装饰'),
 (27, '其他建材'),
 (27, '钢加工'),
 (25, '银行'),
 (25, '农业综合'),
 (25, '供气供热'),
 (24, '化纤'),
 (24, '造纸'),
 (24, '铝'),
 (24, '普钢'),
 (24, '出版业'),
 (23, '汽车整车'),
 (22, '商贸代理'),
 (22, '医药商业'),
 (22, '染料涂料'),
 (21, '水泥'),
 (21, '水力发电'),
 (20, '航空'),
 (20, '矿物制品'),
 (19, '白酒'),
 (19, '路桥'),
 (18, '港口'),
 (18, '玻璃'),
 (18, '饲料'),
 (18, '多元金融'),
 (17, '运输设备'),
 (15, '石油开采'),
 (15, '园区开发'),
 (14, '旅游服务'),
 (14, '铜'),
 (14, '铅锌'),
 (14, '种植业'),
 (13, '水运'),
 (12, '旅游景点'),
 (12, '机床制造'),
 (11, '黄金'),
 (11, '红黄药酒'),
 (11, '水务'),
 (11, '乳制品'),
 (11, '化工机械'),
 (11, '超市连锁'),
 (10, '纺织机械'),
 (10, '酒店餐饮'),
 (10, '轻工机械'),
 (10, '橡胶'),
 (9, '特种钢'),
 (9, '渔业'),
 (9, '公共交通'),
 (9, '石油加工'),
 (9, '汽车服务'),
 (8, '批发业'),
 (8, '船舶'),
 (8, '新型电力'),
 (8, '摩托车'),
 (8, '其他商业'),
 (7, '空运'),
 (7, '日用化工'),
 (7, '公路'),
 (7, '陶瓷'),
 (7, '啤酒'),
 (7, '焦炭加工'),
 (6, '保险'),
 (6, '房产服务'),
 (6, '农用机械'),
 (6, '电信运营'),
 (6, '林业'),
 (6, '石油贸易'),
 (5, '软饮料'),
 (4, '机场'),
 (3, '商品城'),
 (3, '铁路'),
 (2, '电器连锁')]

### 14.2 `HAVING`

* The `HAVING` clause was added to SQL because the WHERE keyword could not be used with aggregate functions.
* `HAVING` is associated with `GROUP BY`, selecting groups which only satisfy `HAVING` condition.

**Syntax**

>```SQL
SELECT column_name(s) FROM table_name WHERE condition GROUP BY column_name(s) HAVING condition;
```

**Example**

In [86]:
%sql SELECT COUNT(*) AS number, area FROM company_info GROUP BY area HAVING COUNT(*)>50 ORDER BY number DESC;

16 rows affected.

[(411, '浙江'),
 (379, '江苏'),
 (304, '北京'),
 (293, '广东'),
 (274, '上海'),
 (266, '深圳'),
 (194, '山东'),
 (131, '福建'),
 (114, '四川'),
 (102, '安徽'),
 (100, '湖南'),
 (96, '湖北'),
 (77, '河南'),
 (74, '辽宁'),
 (55, '河北'),
 (51, '新疆')]

* Rank provinces according to SSH50 companies number.

In [87]:
%sql SELECT count(*) AS number, area FROM company_info RIGHT JOIN sh50 ON company_info.code = sh50.code\
                GROUP BY area ORDER BY number DESC;

13 rows affected.

[(20, '北京'),
 (11, '上海'),
 (4, '深圳'),
 (3, '广东'),
 (2, '江苏'),
 (2, '内蒙'),
 (2, '山东'),
 (1, '贵州'),
 (1, '浙江'),
 (1, '河北'),
 (1, '福建'),
 (1, '山西'),
 (1, '河南')]

## 15. `union`

* The `UNION` operator is used to combine the result-set of two or more SELECT statements.

    * Each `SELECT` statement within `UNION` must have the same number of columns
    * The columns must also have similar data types
    * The columns in each `SELECT` statement must also be in the same order
* The `UNION` operator selects only distinct values by default. To allow duplicate values, use `UNION ALL`.

**Syntax**

>```SQL
SELECT column_name(s) FROM table1
UNION
SELECT column_name(s) FROM table2;
```

**Example**

In [102]:
%sql SELECT code, name FROM company_info WHERE area='广东' UNION ALL \
        SELECT code, name FROM sh50;

343 rows affected.

[(603920, '世运电路'),
 (2908, '德生科技'),
 (2909, '集泰股份'),
 (300716, '国立科技'),
 (300711, '广哈通信'),
 (300620, '光库科技'),
 (300619, '金银河'),
 (300322, '硕贝德'),
 (300720, '海川智能'),
 (2902, '铭普光磁'),
 (603328, '依顿电子'),
 (603322, '超讯通信'),
 (2888, '惠威科技'),
 (300476, '胜宏科技'),
 (600872, '中炬高新'),
 (2841, '视源股份'),
 (2579, '中京电子'),
 (636, '风华高科'),
 (651, '格力电器'),
 (300606, '金太阳'),
 (2792, '通宇通讯'),
 (2745, '木林森'),
 (2292, '奥飞娱乐'),
 (603335, '迪生力'),
 (2035, '华帝股份'),
 (600183, '生益科技'),
 (534, '万泽股份'),
 (300310, '宜通世纪'),
 (2544, '杰赛科技'),
 (300586, '美联新材'),
 (976, '华铁股份'),
 (2446, '盛路通信'),
 (2543, '万和电气'),
 (2311, '海大集团'),
 (300691, '联合光电'),
 (2511, '中顺洁柔'),
 (603386, '广东骏亚'),
 (2212, '南洋股份'),
 (300464, '星徽精密'),
 (603038, '华立股份'),
 (603630, '拉芳家化'),
 (300094, '国联水产'),
 (300098, '高新兴'),
 (600029, '南方航空'),
 (2345, '潮宏基'),
 (2600, '江粉磁材'),
 (300340, '科恒股份'),
 (2572, '索菲亚'),
 (150, '宜华健康'),
 (300498, '温氏股份'),
 (921, '海信科龙'),
 (2017, '东信和平'),
 (2180, '纳思达'),
 (300415, '伊之密'),
 (300503, '昊志机电'),
 (300625, '三雄极光'),
 (2656, '摩登大道'),
 (300687, '赛意信息'),
 (300521, '爱司凯'),
 (333, '美的集团'),
 (2833, '弘亚数控'),
 (300607, '拓斯达'),
 (2449, '国星光电'),
 (502, '绿景控股'),
 (2862, '实丰文化'),
 (2728, '特一药业'),
 (600499, '科达洁能'),
 (2308, '威创股份'),
 (2016, '世荣兆业'),
 (300146, '汤臣倍健'),
 (2465, '海格通信'),
 (300599, '雄塑科技'),
 (507, '珠海港'),
 (2005, '德豪润达'),
 (300460, '惠伦晶体'),
 (2027, '分众传媒'),
 (603833, '欧派家居'),
 (2045, '国光电器'),
 (2663, '普邦股份'),
 (541, '佛山照明'),
 (600004, '白云机场'),
 (2906, '华阳集团'),
 (600866, '星湖科技'),
 (2076, '雪 莱 特'),
 (2240, '威华股份'),
 (600433, '冠豪高新'),
 (529, '广弘控股'),
 (300155, '安居宝'),
 (2791, '坚朗五金'),
 (776, '广发证券'),
 (300639, '凯普生物'),
 (600382, '广东明珠'),
 (603002, '宏昌电子'),
 (2198, '嘉应制药'),
 (2898, '赛隆药业'),
 (2832, '比音勒芬'),
 (603861, '白云电器'),
 (300014, '亿纬锂能'),
 (2870, '香山股份'),
 (300530, '达志科技'),
 (523, '广州浪奇'),
 (2431, '棕榈股份'),
 (600978, '宜华生活'),
 (300089, '文化长城'),
 (2683, '宏大爆破'),
 (603268, '松发股份'),
 (2288, '超华科技'),
 (2141, '贤丰控股'),
 (2884, '凌霄泵业'),
 (603336, '宏辉果蔬'),
 (300050, '世纪鼎利'),
 (2809, '红墙股份'),
 (300043, '星辉娱乐'),
 (2762, '金发拉比'),
 (300616, '尚品宅配'),
 (2855, '捷荣技术'),
 (601238, '广汽集团'),
 (300093, '金刚玻璃'),
 (828, '东莞控股'),
 (2705, '新宝股份'),
 (2433, '太安堂'),
 (603288, '海天味业'),
 (603535, '嘉诚国际'),
 (300404, '博济医药'),
 (2853, '皮阿诺'),
 (2678, '珠江钢琴'),
 (600185, '格力地产'),
 (601515, '东风股份'),
 (2101, '广东鸿图'),
 (2512, '达华智能'),
 (2668, '奥马电器'),
 (603936, '博敏电子'),
 (600685, '中船防务'),
 (600673, '东阳光科'),
 (600589, '广东榕泰'),
 (600332, '白云山'),
 (600242, '中昌数据'),
 (300561, '汇金科技'),
 (300381, '溢多利'),
 (300376, '易事特'),
 (300176, '鸿特精密'),
 (300173, '智慧松德'),
 (300149, '量子高科'),
 (300147, '香雪制药'),
 (300057, '万顺股份'),
 (2741, '光华科技'),
 (2711, '欧浦智网'),
 (2676, '顺威股份'),
 (2638, '勤上股份'),
 (2575, '群兴玩具'),
 (2495, '佳隆股份'),
 (987, '越秀金控'),
 (823, '超声电子'),
 (712, '锦龙股份'),
 (690, '宝新能源'),
 (685, '中山公用'),
 (659, '*ST中富'),
 (601, '韶能股份'),
 (539, '粤电力Ａ'),
 (531, '穗恒运Ａ'),
 (513, '丽珠集团'),
 (603309, '维力医疗'),
 (2295, '精艺股份'),
 (2441, '众业达'),
 (300409, '道氏技术'),
 (2670, '国盛金控'),
 (533, '万 家 乐'),
 (300083, '劲胜智能'),
 (600393, '粤泰股份'),
 (637, '茂化实华'),
 (2420, '毅昌股份'),
 (300482, '万孚生物'),
 (2187, '广百股份'),
 (300004, '南风股份'),
 (2181, '粤 传 媒'),
 (300458, '全志科技'),
 (300526, '中潜股份'),
 (2291, '星期六'),
 (300589, '江龙船艇'),
 (600098, '广州发展'),
 (2611, '东方精工'),
 (2774, '快意电梯'),
 (2031, '巨轮智能'),
 (2177, '御银股份'),
 (603398, '邦宝益智'),
 (2757, '南兴装备'),
 (2319, '乐通股份'),
 (600518, '康美药业'),
 (300177, '中海达'),
 (603043, '广州酒家'),
 (300591, '万里马'),
 (300499, '高澜股份'),
 (300410, '正业科技'),
 (300030, '阳普医疗'),
 (2400, '省广股份'),
 (2842, '翔鹭钨业'),
 (2666, '德联集团'),
 (603898, '好莱客'),
 (601900, '南方传媒'),
 (782, '美达股份'),
 (973, '佛塑科技'),
 (601228, '广州港'),
 (861, '海印股份'),
 (300403, '地尔汉宇'),
 (300143, '星普医科'),
 (2715, '登云股份'),
 (100, 'TCL 集团'),
 (300219, '鸿利智汇'),
 (2317, '众生药业'),
 (600868, '梅雁吉祥'),
 (300529, '健帆生物'),
 (576, '广东甘化'),
 (300359, '全通教育'),
 (300246, '宝莱特'),
 (2152, '广电运通'),
 (2060, '粤 水 电'),
 (2584, '西陇科学'),
 (300053, '欧比特'),
 (300635, '达安股份'),
 (300448, '浩云科技'),
 (2905, '金逸影视'),
 (2030, '达安基因'),
 (2824, '和胜股份'),
 (300328, '宜安科技'),
 (532, '华金资本'),
 (429, '粤高速Ａ'),
 (300242, '明家联合'),
 (2616, '长青集团'),
 (300335, '迪森股份'),
 (2759, '天际股份'),
 (600684, '珠江实业'),
 (300408, '三环集团'),
 (603797, '联泰环保'),
 (2836, '新宏泽'),
 (2732, '燕塘乳业'),
 (600428, '中远海特'),
 (600325, '华发股份'),
 (300221, '银禧科技'),
 (2167, '东方锆业'),
 (573, '粤宏远Ａ'),
 (2846, '英联股份'),
 (524, '岭南控股'),
 (2672, '东江环保'),
 (2249, '大洋电机'),
 (300438, '鹏辉能源'),
 (2709, '天赐材料'),
 (603725, '天安新材'),
 (2233, '塔牌集团'),
 (2503, '搜于特'),
 (2387, '黑牛食品'),
 (717, '韶钢松山'),
 (600728, '佳都科技'),
 (2492, '恒基达鑫'),
 (2063, '远光软件'),
 (2084, '海鸥卫浴'),
 (2348, '高乐股份'),
 (2169, '智光电气'),
 (300417, '南华仪器'),
 (300681, '英搏尔'),
 (600323, '瀚蓝环境'),
 (300424, '航新科技'),
 (300273, '和佳股份'),
 (600894, '广日股份'),
 (893, '东凌国际'),
 (300297, '蓝盾股份'),
 (2776, '柏堡龙'),
 (600048, '保利地产'),
 (2192, '融捷股份'),
 (2054, '德美化工'),
 (603838, '四通股份'),
 (603882, '金域医学'),
 (2723, '金莱特'),
 (300629, '新劲刚'),
 (2425, '凯撒文化'),
 (300063, '天龙集团'),
 (300281, '金明精机'),
 (2806, '华锋股份'),
 (603813, '原尚股份'),
 (2461, '珠江啤酒'),
 (2209, '达 意 隆'),
 (300238, '冠昊生物'),
 (600143, '金发科技'),
 (603608, '天创时尚'),
 (2717, '岭南园林'),
 (2684, '猛狮科技'),
 (600083, '博信股份'),
 (2260, '德奥通航'),
 (603233, '大参林'),
 (2502, '骅威文化'),
 (300311, '任子行'),
 (300562, '乐心医疗'),
 (300723, '一品红'),
 (2911, '佛燃股份'),
 (603993, '洛阳钼业'),
 (601989, '中国重工'),
 (601988, '中国银行'),
 (601985, '中国核电'),
 (601881, '中国银河'),
 (601878, '浙商证券'),
 (601857, '中国石油'),
 (601818, '光大银行'),
 (601800, '中国交建'),
 (601766, '中国中车'),
 (601688, '华泰证券'),
 (601669, '中国电建'),
 (601668, '中国建筑'),
 (601628, '中国人寿'),
 (601601, '中国太保'),
 (601398, '工商银行'),
 (601390, '中国中铁'),
 (601336, '新华保险'),
 (601328, '交通银行'),
 (601318, '中国平安'),
 (601288, '农业银行'),
 (601229, '上海银行'),
 (601211, '国泰君安'),
 (601186, '中国铁建'),
 (601169, '北京银行'),
 (601166, '兴业银行'),
 (601088, '中国神华'),
 (601006, '大秦铁路'),
 (600999, '招商证券'),
 (600958, '东方证券'),
 (600919, '江苏银行'),
 (600887, '伊利股份'),
 (600837, '海通证券'),
 (600606, '绿地控股'),
 (600547, '山东黄金'),
 (600519, '贵州茅台'),
 (600518, '康美药业'),
 (600340, '华夏幸福'),
 (600309, '万华化学'),
 (600111, '北方稀土'),
 (600104, '上汽集团'),
 (600050, '中国联通'),
 (600048, '保利地产'),
 (600036, '招商银行'),
 (600030, '中信证券'),
 (600029, '南方航空'),
 (600028, '中国石化'),
 (600019, '宝钢股份'),
 (600016, '民生银行'),
 (600000, '浦发银行')]

In [130]:
mask = df_company['area']=='广东'
df = df_company[mask][['code', 'name']].append(df_sh50[['code', 'name']])
df.shape

(343, 2)

## 16. EXISTS

* The `EXISTS` operator is used to test for the existence of any record in a subquery.

* The `EXISTS` operator returns true if the subquery returns one or more records.

* You can understand it as a two-level for loop. `EXISTS` operator maps to the inner loop, which will examine each record in outer loop True or False. If True it will be retained.

**Syntax**

>```SQL
SELECT column_name(s) FROM table_name
WHERE EXISTS
(SELECT column_name FROM table_name WHERE condition);
```

**Example**

* Select SSH50 companies in 广东 province

In [107]:
%time %sql SELECT name, area from company_info WHERE name IN (SELECT name FROM sh50) AND area='广东'

3 rows affected.
CPU times: user 3.76 ms, sys: 0 ns, total: 3.76 ms
Wall time: 18.4 ms

[('南方航空', '广东'), ('康美药业', '广东'), ('保利地产', '广东')]

In [120]:
%time %sql SELECT name from sh50 WHERE EXISTS (SELECT * FROM company_info where name=sh50.name and area='广东')

3 rows affected.
CPU times: user 3.9 ms, sys: 0 ns, total: 3.9 ms
Wall time: 201 ms

[('康美药业',), ('保利地产',), ('南方航空',)]

In [116]:
%time %sql SELECT company_info.name, company_info.area FROM company_info RIGHT JOIN sh50 ON company_info.code=sh50.code WHERE company_info.area='广东'

3 rows affected.
CPU times: user 0 ns, sys: 3.86 ms, total: 3.86 ms
Wall time: 12.8 ms

[('南方航空', '广东'), ('康美药业', '广东'), ('保利地产', '广东')]

In [129]:
%time
df = pd.DataFrame()
for name in df_sh50.name:
    df = df.append(df_company[(df_company.name==name)&(df_company.area=='广东')][['name','area']])

df

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.48 µs

      name area
2005  康美药业   广东
3106  保利地产   广东
375   南方航空   广东

* From above example you can see it will be much faster if you can load all the data from database to memory first.

## 17. `ANY` and `ALL`

* The ANY and ALL operators are used with a WHERE or HAVING clause.

* The ANY operator returns true if any of the subquery values meet the condition.

* The ALL operator returns true if all of the subquery values meet the condition.

**Syntax**

>```SQL
SELECT column_name(s) FROM table_name
WHERE column_name operator ANY (SELECT column_name FROM table_name WHERE condition);
```

**Example**

* Select entire information of companies which are listed in SSH50 index.

In [6]:
%time %sql SELECT * FROM company_info WHERE name = ANY (SELECT name FROM sh50)

50 rows affected.
CPU times: user 4.42 ms, sys: 633 µs, total: 5.06 ms
Wall time: 56.5 ms

[(601336, '新华保险', '保险', '北京', 31.25, 3.3, 71477104.0),
 (601318, '中国平安', '保险', '深圳', 14.45, 2.85, 616851584.0),
 (601601, '中国太保', '保险', '上海', 27.63, 2.96, 116817904.0),
 (600519, '贵州茅台', '白酒', '贵州', 31.96, 10.1, 12778004.0),
 (601628, '中国人寿', '保险', '北京', 26.89, 3.05, 286852512.0),
 (600887, '伊利股份', '乳制品', '内蒙', 28.49, 7.75, 4713239.5),
 (600104, '上汽集团', '汽车整车', '上海', 11.54, 1.76, 65232296.0),
 (600029, '南方航空', '空运', '广东', 9.8, 1.82, 21133400.0),
 (601878, '浙商证券', '证券', '浙江', 56.6, 4.66, 5144893.0),
 (600050, '中国联通', '电信运营', '上海', 142.59, 2.22, 59056808.0),
 (601881, '中国银河', '证券', '北京', 30.29, 2.13, 24398524.0),
 (600000, '浦发银行', '银行', '上海', 6.64, 0.96, 606383680.0),
 (600019, '宝钢股份', '普钢', '上海', 11.85, 1.17, 34661280.0),
 (600030, '中信证券', '证券', '深圳', 21.08, 1.52, 63177336.0),
 (600016, '民生银行', '银行', '北京', 5.72, 0.85, 571252480.0),
 (600340, '华夏幸福', '区域地产', '河北', 10.83, 3.34, 33648380.0),
 (600958, '东方证券', '证券', '上海', 28.55, 2.4, 22343832.0),
 (600036, '招商银行', '银行', '深圳', 8.71, 1.56, 616923904.0),
 (600999, '招商证券', '证券', '深圳', 23.44, 1.66, 25777122.0),
 (601688, '华泰证券', '证券', '江苏', 23.13, 1.69, 37462496.0),
 (600518, '康美药业', '中成药', '广东', 26.56, 3.59, 6533670.5),
 (601169, '北京银行', '银行', '北京', 6.42, 0.87, 227522592.0),
 (600837, '海通证券', '证券', '上海', 20.41, 1.44, 52946080.0),
 (601211, '国泰君安', '证券', '上海', 18.84, 1.46, 41555676.0),
 (601818, '光大银行', '银行', '北京', 5.51, 0.77, 403041408.0),
 (600919, '江苏银行', '银行', '江苏', 7.49, 1.03, 173756544.0),
 (600111, '北方稀土', '小金属', '内蒙', 111.69, 5.9, 2202781.75),
 (601166, '兴业银行', '银行', '福建', 5.6, 0.92, 640699328.0),
 (601229, '上海银行', '银行', '上海', 8.63, 1.08, 175999888.0),
 (600547, '山东黄金', '黄金', '山东', 46.69, 3.43, 4219631.5),
 (601800, '中国交建', '建筑施工', '北京', 15.3, 1.38, 88370472.0),
 (601006, '大秦铁路', '铁路', '山西', 8.77, 1.35, 12906953.0),
 (601328, '交通银行', '银行', '上海', 6.25, 0.76, 893579072.0),
 (601985, '中国核电', '新型电力', '北京', 21.96, 2.79, 30007324.0),
 (601988, '中国银行', '银行', '北京', 5.87, 0.83, 1942243712.0),
 (600309, '万华化学', '化工原料', '山东', 9.64, 4.19, 6275300.0),
 (601288, '农业银行', '银行', '北京', 5.53, 0.89, 2092311808.0),
 (601857, '中国石油', '石油开采', '北京', 66.33, 1.29, 244611104.0),
 (600606, '绿地控股', '全国地产', '上海', 10.43, 1.52, 77101312.0),
 (603993, '洛阳钼业', '小金属', '河南', 68.25, 3.92, 10020716.0),
 (600048, '保利地产', '全国地产', '广东', 11.23, 1.31, 63262392.0),
 (601989, '中国重工', '船舶', '北京', 84.29, 1.95, 20866086.0),
 (601669, '中国电建', '建筑施工', '北京', 15.07, 1.48, 58281880.0),
 (601398, '工商银行', '银行', '北京', 6.82, 1.04, 2576479744.0),
 (601088, '中国神华', '煤炭开采', '北京', 9.04, 1.47, 56003400.0),
 (600028, '中国石化', '石油加工', '北京', 14.41, 1.03, 147665504.0),
 (601668, '中国建筑', '建筑施工', '北京', 8.25, 1.37, 152710720.0),
 (601390, '中国中铁', '建筑施工', '北京', 13.66, 1.34, 78568864.0),
 (601186, '中国铁建', '建筑施工', '北京', 11.47, 1.15, 82964336.0),
 (601766, '中国中车', '运输设备', '北京', 34.49, 2.66, 37577796.0)]

In [7]:
%time %sql SELECT * FROM company_info WHERE name IN  (SELECT name FROM sh50)

50 rows affected.
CPU times: user 4.69 ms, sys: 0 ns, total: 4.69 ms
Wall time: 58.1 ms

[(601336, '新华保险', '保险', '北京', 31.25, 3.3, 71477104.0),
 (601318, '中国平安', '保险', '深圳', 14.45, 2.85, 616851584.0),
 (601601, '中国太保', '保险', '上海', 27.63, 2.96, 116817904.0),
 (600519, '贵州茅台', '白酒', '贵州', 31.96, 10.1, 12778004.0),
 (601628, '中国人寿', '保险', '北京', 26.89, 3.05, 286852512.0),
 (600887, '伊利股份', '乳制品', '内蒙', 28.49, 7.75, 4713239.5),
 (600104, '上汽集团', '汽车整车', '上海', 11.54, 1.76, 65232296.0),
 (600029, '南方航空', '空运', '广东', 9.8, 1.82, 21133400.0),
 (601878, '浙商证券', '证券', '浙江', 56.6, 4.66, 5144893.0),
 (600050, '中国联通', '电信运营', '上海', 142.59, 2.22, 59056808.0),
 (601881, '中国银河', '证券', '北京', 30.29, 2.13, 24398524.0),
 (600000, '浦发银行', '银行', '上海', 6.64, 0.96, 606383680.0),
 (600019, '宝钢股份', '普钢', '上海', 11.85, 1.17, 34661280.0),
 (600030, '中信证券', '证券', '深圳', 21.08, 1.52, 63177336.0),
 (600016, '民生银行', '银行', '北京', 5.72, 0.85, 571252480.0),
 (600340, '华夏幸福', '区域地产', '河北', 10.83, 3.34, 33648380.0),
 (600958, '东方证券', '证券', '上海', 28.55, 2.4, 22343832.0),
 (600036, '招商银行', '银行', '深圳', 8.71, 1.56, 616923904.0),
 (600999, '招商证券', '证券', '深圳', 23.44, 1.66, 25777122.0),
 (601688, '华泰证券', '证券', '江苏', 23.13, 1.69, 37462496.0),
 (600518, '康美药业', '中成药', '广东', 26.56, 3.59, 6533670.5),
 (601169, '北京银行', '银行', '北京', 6.42, 0.87, 227522592.0),
 (600837, '海通证券', '证券', '上海', 20.41, 1.44, 52946080.0),
 (601211, '国泰君安', '证券', '上海', 18.84, 1.46, 41555676.0),
 (601818, '光大银行', '银行', '北京', 5.51, 0.77, 403041408.0),
 (600919, '江苏银行', '银行', '江苏', 7.49, 1.03, 173756544.0),
 (600111, '北方稀土', '小金属', '内蒙', 111.69, 5.9, 2202781.75),
 (601166, '兴业银行', '银行', '福建', 5.6, 0.92, 640699328.0),
 (601229, '上海银行', '银行', '上海', 8.63, 1.08, 175999888.0),
 (600547, '山东黄金', '黄金', '山东', 46.69, 3.43, 4219631.5),
 (601800, '中国交建', '建筑施工', '北京', 15.3, 1.38, 88370472.0),
 (601006, '大秦铁路', '铁路', '山西', 8.77, 1.35, 12906953.0),
 (601328, '交通银行', '银行', '上海', 6.25, 0.76, 893579072.0),
 (601985, '中国核电', '新型电力', '北京', 21.96, 2.79, 30007324.0),
 (601988, '中国银行', '银行', '北京', 5.87, 0.83, 1942243712.0),
 (600309, '万华化学', '化工原料', '山东', 9.64, 4.19, 6275300.0),
 (601288, '农业银行', '银行', '北京', 5.53, 0.89, 2092311808.0),
 (601857, '中国石油', '石油开采', '北京', 66.33, 1.29, 244611104.0),
 (600606, '绿地控股', '全国地产', '上海', 10.43, 1.52, 77101312.0),
 (603993, '洛阳钼业', '小金属', '河南', 68.25, 3.92, 10020716.0),
 (600048, '保利地产', '全国地产', '广东', 11.23, 1.31, 63262392.0),
 (601989, '中国重工', '船舶', '北京', 84.29, 1.95, 20866086.0),
 (601669, '中国电建', '建筑施工', '北京', 15.07, 1.48, 58281880.0),
 (601398, '工商银行', '银行', '北京', 6.82, 1.04, 2576479744.0),
 (601088, '中国神华', '煤炭开采', '北京', 9.04, 1.47, 56003400.0),
 (600028, '中国石化', '石油加工', '北京', 14.41, 1.03, 147665504.0),
 (601668, '中国建筑', '建筑施工', '北京', 8.25, 1.37, 152710720.0),
 (601390, '中国中铁', '建筑施工', '北京', 13.66, 1.34, 78568864.0),
 (601186, '中国铁建', '建筑施工', '北京', 11.47, 1.15, 82964336.0),
 (601766, '中国中车', '运输设备', '北京', 34.49, 2.66, 37577796.0)]

* Return entire infomation of the company which has minimum totoalAsset.

In [9]:
%time %sql SELECT * FROM company_info WHERE totalAssets <= ALL (SELECT totalAssets FROM company_info)

1 rows affected.
CPU times: user 0 ns, sys: 3.78 ms, total: 3.78 ms
Wall time: 12.2 ms

[(600870, '厦华电子', '家用电器', '福建', 0.0, 408.81, 5229.16)]

In [11]:
%time %sql SELECT * FROM company_info WHERE totalAssets <= (SELECT MIN(totalAssets) FROM company_info)

1 rows affected.
CPU times: user 3.77 ms, sys: 0 ns, total: 3.77 ms
Wall time: 12.5 ms

[(600870, '厦华电子', '家用电器', '福建', 0.0, 408.81, 5229.16)]